spring:
  datasource:
    test1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123
      type: com.alibaba.druid.pool.DruidDataSource

    test2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123
      type: com.alibaba.druid.pool.DruidDataSource
